#! /usr/bin/env bash
#
# Automatically adds the issue number to the commit message.
#

function get_issue_number() {
  branch_name=$(git branch --show-current) # Get the current branch name
  issues=$(echo "$branch_name" | grep -oP "^$GIT_ISSUE_REGEX|/$GIT_ISSUE_REGEX") # Get the issue name
  # Select the last one, removing the slash if it exists
  # shellcheck disable=SC2086 # We want $issues to split
  last_issue=$(echo $issues | awk '{print $NF}' | sed 's/\///g')
  echo "$last_issue"
}

ISSUE_NUMBER=$(get_issue_number)
MSG=$(head -n 1 "$1")
if [[ "$MSG" != "$ISSUE_NUMBER"* ]] && [[ "$MSG" != "fixup!"* ]] && [[ "$MSG" != "amend!"* ]] && [[ "$MSG" != "squash!"* ]]; then
  echo "$ISSUE_NUMBER"' '"$(cat "$1")" > "$1"
fi
