#! /usr/bin/env bash

REPO_ROOT="$(
  cd "$(git rev-parse --show-toplevel)" >/dev/null 2>&1
  pwd -P
)"
readonly REPO_ROOT

HOOKS_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
readonly HOOKS_ROOT
export HOOKS_ROOT

MERGE_HASH=$(git rev-parse -q --verify MERGE_HEAD 2>/dev/null)
readonly MERGE_HASH
if [ -n "$MERGE_HASH" ]; then
  # Merge commit
  echo "Merge commit; skipping hooks"
  exit 0
fi

REBASE_APPLY_PATH="${REPO_ROOT}/.git/rebase-apply"
REBASE_MERGE_PATH="${REPO_ROOT}/.git/rebase-merge"
IS_AMEND=$(ps -ocommand= -p $PPID | grep -e '--amend')
readonly IS_AMEND

if [ -e "${REBASE_APPLY_PATH}" ] || [ -e "${REBASE_MERGE_PATH}" ]; then
  # Rebase commit
  echo "Rebase commit; skipping hooks"
  exit 0
fi

# Normal commit

# Get the files that have changed
git_dir=$(git rev-parse --show-toplevel)/
export git_dir

# C++ files
"$HOOKS_ROOT"/scripts/precommit/cxx.bash || exit $?

# C# files
"$HOOKS_ROOT"/scripts/precommit/csharp.bash || exit $?

# CMake files
"$HOOKS_ROOT"/scripts/precommit/cmake.bash || exit $?

# Python files
"$HOOKS_ROOT"/scripts/precommit/python.bash || exit $?

exit 0
