#! /usr/bin/env bash

HOOKS_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
readonly HOOKS_ROOT
export HOOKS_ROOT

MERGE_HASH=$(git rev-parse -q --verify MERGE_HEAD 2>/dev/null)
readonly MERGE_HASH
if [ -n "$MERGE_HASH" ]; then
  # Merge commit
  echo "Merge commit; skipping hooks"
  exit 0
fi

REBASE_HASH=$(git rev-parse -q --verify REBASE_HEAD 2>/dev/null)
readonly REBASE_HASH
IS_AMEND=$(ps -ocommand= -p $PPID | grep -e '--amend');
readonly IS_AMEND
if [ -n "$REBASE_HASH" ] && [ -z "$IS_AMEND" ]; then
  # Rebase commit
  echo "Rebase commit; skipping hooks"
  exit 0
fi

# Normal commit

# Get the files that have changed
git_dir=$(git rev-parse --show-toplevel)/
export git_dir

# C++ files
"$HOOKS_ROOT"/scripts/precommit/cxx.bash || exit $?

# C# files
"$HOOKS_ROOT"/scripts/precommit/csharp.bash || exit $?

# CMake files
"$HOOKS_ROOT"/scripts/precommit/cmake.bash || exit $?

# Python files
"$HOOKS_ROOT"/scripts/precommit/python.bash || exit $?

exit 0
